### ISSUE TITLE
Update after 2.8.3 to 3.1.0 or later

### ISSUE THREAD

**Issue by DavidSichau** [webauthn-open-source/fido2-lib#96]
After updating the library to 2.8.3 from 3.1.0.

We observer the following error:

```
error parsing ASN.1 
```

We have not changed any parts of our code.

We use yubikeys 5 with this library.

**Comment by Hexagon** [comment]
Interesting!

Have you tried 3.1.7? 
Which version of node?
Which version is the yubikey 5s?
Which configuration do you initialize fido2-lib with?
Can you share more info about the setup?

**Comment by DavidSichau** [comment]
Have you tried 3.1.7: yes
Which version of node: v14.19.1
Which version is the yubikey 5s: https://support.yubico.com/hc/en-us/articles/360013656980-YubiKey-5-NFC and https://support.yubico.com/hc/en-us/articles/360016649339-YubiKey-5C-NFC
Which configuration do you initialize fido2-lib with:
```
const f2l = new Fido2Lib({
  timeout: 30000,
  rpId: expert.ethz.ch,
  rpName: 'expert',
  challengeSize: 128,
  authenticatorUserVerification: 'discouraged',
  attestation: 'direct',
  cryptoParams: [-7],
});
```

Can you share more info about the setup:
We use it in a meteor environment and on step we need to to is to encode and decode the data, as we cannot send binary data via meteor to the server. We encode and decode the data to base64 using the following library: https://www.npmjs.com/package/base64-arraybuffer

Do https://56k.guru/webauthn-debugger/ (works on client side only) work with you yubikeys: Yes this works.

**Comment by Hexagon** [comment]
Great!

Do you have a traceback of where in fido2-lib the error occur, this would help in identfying exactly what goes wrong.

It do spontaneously feel like it has to do with the base64 encoding/decoding on your end. Some (many) values of Webauthn it expected to be in base64**url**-format, if you accidentally base64-encode a base64-**url**-string, and forget to base64-decode it back into base64url, unexpected thing could happen.

fido2-lib _should_ handle the case of supplying a correct base64 instead of a base64url. A traceback would really help to identify is there an internal issue regarding this on our end.
 
Take a close look on whats encoded on your client, and whats decoded on your server side, to see any kind of mismatch.

**Comment by JamesCullum** [comment]
Bonus points if you can supply us with the exact request you're receiving - then we can better emulate it on our side and build a test case for the future from it 👍

**Comment by DavidSichau** [comment]
Thanks for your support. Here the request that is sent with the data and the traceback.

The error occures in: `assertionResult`

I send the following data into this method:

AssertionResult:
```
 {
 rawId: ArrayBuffer {
    [Uint8Contents]: <74 88 a3 47 32 1e 4e b1 0b 14 cf e0 4e c6 fe f6 ea 71 30 67 6f 20 25 9a e3 19 8d ac db fd 56 74 cb ab 1f 5c 2f 51 5b 2a e9 77 7b 72 e4 ae 99 ba ec aa 09 12 8f d1 21 92 e3 82 a9 82 31 46 d1 0c>,
     byteLength: 64
  },
  response: {
    clientDataJSON: 'eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoidUxHWGxLUzM5Z2EzaUJSM3hNNEZzamFvTHhyekp6d1I4SzFKZ1JETkhtdWItMWFsRUN4Y1hfUV9xN1hkVnhENk53LVFMZkZnWlNSZDc1dndFbUhLLWhEYWNEdVNOeU1zWFNxc3NRU3ZlZGFKa2dfblhFSlotOF9jQVc5X0R5S0RDWlZRRDR3X1VEMVV3dl9PWlZtMHpUX2pRdThINkRFTEFaLXZLVVdlNXZRIiwib3JpZ2luIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ==',
   authenticatorData: ArrayBuffer {
     [Uint8Contents]: <49 96 0d e5 88 0e 8c 68 74 34 17 0f 64 76 60 5b 8f e4 ae b9 a2 86 32 c7 99 5c f3 ba 83 1d 97 63 01 00 00 00 26>,
      byteLength: 37
    },
     signature: 'MEUCIQDuKI5sqRD91f7d+YGihiVIo81eWEaDyXOTTOJVRNlXdQIgFFZY5OKbTaYMLFPSHVnfaz1NC4gJMZ7qpUY+bAuV3XQ=',
    userHandle: undefined
  }
 }
```
ExpectedAssertionResult:
```
{
   challenge: 'uLGXlKS39ga3iBR3xM4FsjaoLxrzJzwR8K1JgRDNHmub+1alECxcX/Q/q7XdVxD6Nw+QLfFgZSRd75vwEmHK+hDacDuSNyMsXSqssQSvedaJkg/nXEJZ+8/cAW9/DyKDCZVQD4w/UD1Uwv/OZVm0zT/jQu8H6DELAZ+vKUWe5vQ=',
   origin: 'http://localhost:3000',
   factor: 'either',
   prevCounter: 2,
   userHandle: null,
   publicKey: '-----BEGIN PUBLIC KEY-----\n' +
     'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFBBr49saY4KmO7LJT4YYzsidYeVy\n' +
     'd5u9259F7ZubKTx8TwOKi8phw2TF9iUw81KxRQBZlFblkM4pef2ec2WM5w==\n' +
     '-----END PUBLIC KEY-----'
 }
```

Traceback:

```
 Error: error parsing ASN.1
     at PublicKey.fromPem (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:904:10)
     at verifySignature (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:1497:23)
     at Fido2AssertionResult.validateAssertionSignature (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:2247:18)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
     at Fido2AssertionResult.validate (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:3082:3)
     at Fido2AssertionResult.create (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:3003:3)
  => awaited here:
     at Function.Promise.await (/home/sichaud/.meteor/packages/promise/.0.12.0.jxkz03.7h32++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
     at imports/api/methods/serverOnly/webauthMethods.ts:200:13

```

**Comment by DavidSichau** [comment]
Hi thanks for your updated. We still have the error in the latest 3.2.2 version.

AssertionResult:

```
{
  rawId: ArrayBuffer {
    [Uint8Contents]: <5e ac 8c 0d f9 e4 d8 d6 4b 01 a9 0d 36 83 ef 7d fd 51 8a 31 ad 8e 1a fe a6 01 65 58 64 a6 4d 21 e1 56 d9 3e d4 d2 b4 c7 83 7f 19 65 50 fc e5 c2 a0 d0 7e 7e 6e 74 9a f4 43 d0 65 8d 8f 42 ef 9e>,
    byteLength: 64
  },
  response: {
    clientDataJSON: 'eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiX1JJaU8wZWNVS0R3eDZNVkllZ0xfSkN1emJQVFJSNUY1emJlVnpJTWYzcnFuQjAxZ1VmaWRHT0tiY0MtMXhnU0JqMndzNDR1TndJQ3JvOW9BMGdGRXU3T3Rmek9nR2UzSDdxbjc0clRlWlR4T2p6MEhpWEtLR1dTYzc0WFRYWXJQdnp3dUVZdE1Ea1RfWW5sTndjdlRkdS1XU25mZkZwWHQwaXFESDFHSkFFIiwib3JpZ2luIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ==',
    authenticatorData: ArrayBuffer {
      [Uint8Contents]: <49 96 0d e5 88 0e 8c 68 74 34 17 0f 64 76 60 5b 8f e4 ae b9 a2 86 32 c7 99 5c f3 ba 83 1d 97 63 01 00 00 00 09>,
      byteLength: 37
    },
    signature: 'MEYCIQCmX3Uwppc3BkMjtJ9Vo+Aem2SNUFWptERx7pruGfQW2QIhAKHj0ohnWDAdTOyRvXe3jSbOv9IgIgGJHLge1VMaM08d',
    userHandle: undefined
  }
}
```
ExpectedAssertionResult:

```
{
  challenge: '/RIiO0ecUKDwx6MVIegL/JCuzbPTRR5F5zbeVzIMf3rqnB01gUfidGOKbcC+1xgSBj2ws44uNwICro9oA0gFEu7OtfzOgGe3H7qn74rTeZTxOjz0HiXKKGWSc74XTXYrPvzwuEYtMDkT/YnlNwcvTdu+WSnffFpXt0iqDH1GJAE=',
  origin: 'http://localhost:3000',
  factor: 'either',
  prevCounter: 3,
  userHandle: null,
  publicKey: '-----BEGIN PUBLIC KEY-----\n' +
    'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/jce8X8C5N4qGIDHVO4MwczKscvc\n' +
    'iilGQgFpcnQtPIYkmNz82D/lXLuGBhKIC8i9ogQDVL2wu233SudgqY1CWg==\n' +
    '-----END PUBLIC KEY-----'
}
```

Traceback of Error:

```
Error: error parsing ASN.1
    at PublicKey.fromPem (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:904:10)
    at verifySignature (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:1497:23)
    at Fido2AssertionResult.validateAssertionSignature (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:2250:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Fido2AssertionResult.validate (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:3085:3)
    at Fido2AssertionResult.create (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/fido2-lib/dist/main.cjs:3006:3)
 => awaited here:
    at Function.Promise.await (/home/sichaud/.meteor/packages/promise/.0.12.0.jxkz03.7h32++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at imports/api/methods/serverOnly/webauthMethods.ts:199:13
    at /home/sichaud/.meteor/packages/promise/.0.12.0.jxkz03.7h32++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
